# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48d9f6fd18c7b8599f937ec0d1cab6550f8a8010e5d4673bdef5318a0c747e6c5a44e7e5ac7ae84f7d7db0726a6922cadbd1ac2ab9077ab828fdbbf1ae2426bd

test:
  secret_key_base: 758f9d99a6ce03868dbd8d3da4d9ad6b96c4f8606f95be391d5873e4ccf4241ffdb96a2d148437197835ecef6f6dfaa359f9bcb68e80c7ae4fe6c5918ac4c735

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
